fix: resolve compilation errors with openapi31 and jq features
Fix #42:

1. Format `Error::jq_filter_error` such as to make Into<String>
fit the constraint.
2. Return the Spec struct value from the match arms instead of
consuming with `;`

Testing:
  CI built in Arch chroot successfully

Co-authored-by: RageLtMan <rageltman [at] sempervictus>